function [a,b,c,d] = autoGen_hermitePolyCoeff(T,p0,v0,p1,v1)
%AUTOGEN_HERMITEPOLYCOEFF
%    [A,B,C,D] = AUTOGEN_HERMITEPOLYCOEFF(T,P0,V0,P1,V1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Oct-2021 10:58:55

a = p0;
if nargout > 1
    b = v0;
end
if nargout > 2
    t2 = T.*v1;
    c = -1.0./T.^2.*(p0.*3.0-p1.*3.0+t2+T.*v0.*2.0);
end
if nargout > 3
    d = 1.0./T.^3.*(p0.*2.0-p1.*2.0+t2+T.*v0);
end
