function Jac_foot_base = autoGen_JacFootBase(q1,q2,q3,q4,j1z,l1,l2)
%AUTOGEN_JACFOOTBASE
%    JAC_FOOT_BASE = AUTOGEN_JACFOOTBASE(Q1,Q2,Q3,Q4,J1Z,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Oct-2021 14:23:07

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = sin(q1);
t7 = sin(q2);
t8 = sin(q3);
t9 = sin(q4);
t10 = l2.*t5;
t11 = t2.*t4;
t12 = t2.*t8;
t13 = t4.*t6;
t14 = t6.*t8;
t20 = l2.*t3.*t4.*t9;
t15 = l1+t10;
t16 = t7.*t14;
t17 = t7.*t11;
t18 = t7.*t12;
t19 = t7.*t13;
t21 = -t16;
t22 = -t17;
t23 = t12+t19;
t24 = t13+t18;
t25 = t11+t21;
t26 = t14+t22;
t27 = l2.*t9.*t23;
t28 = l2.*t9.*t26;
Jac_foot_base = reshape([t15.*t26+l2.*t9.*t24,-t15.*t23-l2.*t9.*t25,0.0,-t3.*t13.*t15+l2.*t3.*t9.*t14,t3.*t11.*t15-l2.*t3.*t9.*t12,t4.*t7.*t15-l2.*t7.*t8.*t9,t27-t15.*t25,t28-t15.*t24,t20+t3.*t8.*t15,t27-t10.*t25,t28-t10.*t24,t20+t3.*t8.*t10],[3,4]);
