function [a,b,c,d,e] = autoGen_4orderPolyCoeff(T,p0,v0,a0,p1,v1)
%AUTOGEN_4ORDERPOLYCOEFF
%    [A,B,C,D,E] = AUTOGEN_4ORDERPOLYCOEFF(T,P0,V0,A0,P1,V1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Oct-2021 16:01:47

a = p0;
if nargout > 1
    b = v0;
end
if nargout > 2
    c = a0./2.0;
end
if nargout > 3
    t2 = T.^2;
    t3 = a0.*t2;
    d = -1.0./T.^3.*(p0.*4.0-p1.*4.0+t3+T.*v0.*3.0+T.*v1);
end
if nargout > 4
    e = (1.0./t2.^2.*(p0.*6.0-p1.*6.0+t3+T.*v0.*4.0+T.*v1.*2.0))./2.0;
end
